### ISSUE TITLE
Better Check Mode and Diff Support

### ISSUE THREAD

**Issue by pgassmann** [markuman/hetzner_dns#1]
Thank you for this useful ansible module. The module currently has limited check mode support. I have the following requests:

- **Show diffs for changing records**. in check mode, `record` seems to work correctly  and only show changed when there is a change. it would be useful to see what's changing.

- **zone_info and record_info should work by default in check_mode**. It can be used in checkmode by setting `check_mode: False` on a task

**Comment by markuman** [comment]
I can add `past_record`.  
On a change value, it will return 

```
ok: [localhost] => {
    "msg": {
        "changed": true,
        "failed": false,
        "past_record": {
            "created": "2021-04-12 17:44:48.881 +0000 UTC",
            "id": "e0ffb7aa0eee61a3f540055c50ff10d2",
            "modified": "2021-04-12 17:44:48.881 +0000 UTC",
            "name": "hetzner_dns_ansible_collection",
            "ttl": 300,
            "type": "CNAME",
            "value": "osuv.de.",
            "zone_id": "jbKFKm7sUEf8DEj4HgHram"
        },
        "record_id": "e0ffb7aa0eee61a3f540055c50ff10d2",
        "record_info": {
            "record": {
                "name": "hetzner_dns_ansible_collection",
                "ttl": 60,
                "type": "CNAME",
                "value": "osuv.de.",
                "zone_id": "jbKFKm7sUEf8DEj4HgHram"
            }
        }
    }
}
```

It will return on both, `check_mode: yes` or `check_mode: no`


```yml
    - name: modify record change in check_mode
      markuman.hetzner_dns.record:
        zone_name: "{{ TEST_ZONE }}"
        name: hetzner_dns_ansible_collection
        value: osuv.de.
        type: CNAME
        ttl: 60
      check_mode: yes
      register: RECORD

    - name: change record check_mode
      assert:
        that:
          - RECORD is changed
          - RECORD.record_info.record.ttl == 60
          - RECORD.past_record.ttl == 300

    - name: modify record change
      markuman.hetzner_dns.record:
        zone_name: "{{ TEST_ZONE }}"
        name: hetzner_dns_ansible_collection
        value: osuv.de.
        type: CNAME
        ttl: 60
      register: RECORD

    - name: change record
      assert:
        that:
          - RECORD is changed
          - RECORD.record_info.record.ttl == 60
          - RECORD.past_record.ttl == 300
``` 


> zone_info and record_info should work by default in check_mode. It can be used in checkmode by setting check_mode: False on a task

I think the issue is, that the modules does not support `check_mode`.

```
TASK [fetch zone info in check_mode] **********************************************************************************************************************************************************************************************************************************
skipping: [localhost]
```

It's easy to add.  
Thx for your feedback and requests.
