### ISSUE TITLE
move over to community.dns

### ISSUE THREAD

**Issue by markuman** [markuman/hetzner_dns#6]
After some conversation with @felixfontein in #ansible-community, we try to move hetzner dns functionality over to https://github.com/ansible-collections/community.dns/

**Comment by markuman** [comment]
https://github.com/ansible-collections/community.dns/pull/27

**Comment by felixfontein** [comment]
community.dns now has a set of Hetzner plugins which should be able to do everything that the plugins in this collections do. They are not a complete drop-in replacement, since the record_info plugin works somewhat differently, and the record plugin from this collection needs to be replaced with hetzner_dns_record and hetzner_dns_record_set depending on how it is used (mainly depending on what's the value of the `purge` option). Also right now the zone_info module doesn't return all the extra information; this is something I want to work on next (both Hetzner and Hosttech provide a lot more information than the module currently returns). Something else missing is documentation :)

**Comment by felixfontein** [comment]
I created the community.dns 2.0.0-a1 prerelease so it's easier to test this. Please test it and report potential problems, suggestions for improvements, etc.! Plugin and module documentation can be found here: https://ansible.fontein.de/collections/community/dns/

**Comment by markuman** [comment]
# migration path is

I guess for most users it's just.

1.  take care about `state` value

```yml
---
- name: dns setup
  hosts: localhost
  connection: local

  tasks:
    - name: set dns record with markuman.hetzner_dns
      markuman.hetzner_dns.record:
        name: localhost
        type: A
        value: 127.0.0.1
        ttl: 60
        zone_name: osuv.de

    - name: set same record with community.dns
      community.dns.hetzner_dns_record:
        name: localhost
        type: A
        value: 127.0.0.1
        ttl: 60
        zone_name: osuv.de
        state: present
```

# maintenance path for the future is

```
[DEPRECATION WARNING]: Alias 'name' is deprecated. See the module docs for more information. This feature will be removed from community.dns in version 3.0.0. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

use `prefix` instead of `name` parameter

```diff
     - name: set same record with community.dns
       community.dns.hetzner_dns_record:
-        name: localhost
+        prefix: localhost
         type: A
         value: 127.0.0.1
         ttl: 60
         zone_name: osuv.de
         state: present
```

**Comment by felixfontein** [comment]
I created docs and a migration guide: ansible-collections/community.dns#44

**Comment by pgassmann** [comment]
great to see that this module will be adapted more widely. 
One question @markuman : Did you address the diff format mismatch from https://github.com/markuman/hetzner_dns/issues/4#issuecomment-824693485? Sorry, I did not get to work further on managing entries, but we currently use it to create automatic backups of zones. 

diff support would be really useful.

**Comment by markuman** [comment]
@pgassmann latest version (1.6.1) of `markuman.hetzner_dns`, diff mode looks like this

```
TASK [test diff] ************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 - name: hetzner_dns_ansible_collection
   ttl: 300
   type: CNAME
-  value: osuv.de.
+  value: ansible.com.

changed: [localhost]
```

It's [improved/fixed since 1.5.0](https://github.com/markuman/hetzner_dns/commit/3187b32d23e2135badd5bbd9675d1757784f690b)

**Comment by felixfontein** [comment]
@pgassmann please note that the modules in community.dns are different modules than the ones in this collection. If you are relying on specific behavior, you should test whether the new modules work for you as well, and if not provide feedback. Right now we're still able to make breaking changes to the interface; once community.dns 2.0.0 is released, only backwards compatible changes are allowed.

**Comment by markuman** [comment]
the diff output is different between `community.dns` 2.0.0-a1 and `markuman.hetzner_dns` 1.6.1

#### example playbook

```yml
---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: diff tests
      block:
        - name: create record for diff testing
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: hetzner_dns_ansible_collection
            value: "osuv.de."
            type: CNAME
            ttl: 300

        - name: markuman.hetzner_dns | test diff on change record
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: hetzner_dns_ansible_collection
            value: "ansible.com."
            type: CNAME
            ttl: 300
            state: present
          check_mode: yes

        - name: markuman.hetzner_dns | test diff on new record
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: blabla
            value: "ansible.com."
            type: CNAME
            ttl: 300
            state: present
          check_mode: yes

        - name: community.dns | test diff on change record
          community.dns.hetzner_dns_record:
            zone_name: osuv.de
            name: hetzner_dns_ansible_collection
            value: "ansible.com."
            type: CNAME
            ttl: 300
            state: present
          check_mode: yes

        - name: community.dns | test diff on new record
          community.dns.hetzner_dns_record:
            zone_name: osuv.de
            name: blabla
            value: "ansible.com."
            type: CNAME
            ttl: 300
            state: present
          check_mode: yes
```

### output

```
TASK [markuman.hetzner_dns | test diff on change record] ****************************************************************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 - name: hetzner_dns_ansible_collection
   ttl: 300
   type: CNAME
-  value: osuv.de.
+  value: ansible.com.

changed: [localhost]

TASK [markuman.hetzner_dns | test diff on new record] *******************************************************************************************************************************************************************************
--- before
+++ after
@@ -1 +1,4 @@
-[]
+- name: blabla
+  ttl: 300
+  type: CNAME
+  value: ansible.com.

changed: [localhost]

TASK [community.dns | test diff on change record] ***********************************************************************************************************************************************************************************
--- before
+++ after
@@ -1 +1,7 @@
-{}
+{
+    "prefix": "hetzner_dns_ansible_collection",
+    "record": "hetzner_dns_ansible_collection.osuv.de",
+    "ttl": 300,
+    "type": "CNAME",
+    "value": "ansible.com."
+}

[DEPRECATION WARNING]: Alias 'name' is deprecated. See the module docs for more information. This feature will be removed from community.dns in version 3.0.0. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
changed: [localhost]

TASK [community.dns | test diff on new record] **************************************************************************************************************************************************************************************
--- before
+++ after
@@ -1 +1,7 @@
-{}
+{
+    "prefix": "blabla",
+    "record": "blabla.osuv.de",
+    "ttl": 300,
+    "type": "CNAME",
+    "value": "ansible.com."
+}

changed: [localhost]

PLAY RECAP **************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by markuman** [comment]
@felixfontein I think the `test diff on change record` must be improved, that it only mark the changing parameters.  
About new records, I've got no preferences it if is a list or a dict.

**Comment by felixfontein** [comment]
@markuman the diff is working as expected. You are asking the module to create another CNAME record (which is illegal, but the module doesn't know it - since you're using check mode, it shows you that it creates a new CNAME record). If you would do it without check mode, the API call would fail with `422 Unprocessable Entity: taken  hetzner_dns_ansible_collection`. Right now `hetzner_dns_record` is matching records by prefix and value; the only thing modified is the TTL.

**Comment by markuman** [comment]
> the only thing modified is the TTL.

 no. TTL was not affected.  
But you're right.

Migration-path for changing existing record is this

```yml
---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: test create
      block:
        - name: test gracefull error handling
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: hetzner_dns_ansible_collection
            value: "osuv.de."
            type: CNAME
            ttl: 300

        - name: markuman.hetzner_dns | test diff on change record
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: hetzner_dns_ansible_collection
            value: "ansible.com."
            type: CNAME
            ttl: 300
            state: present

        - name: community.dns | test diff on change record
          community.dns.hetzner_dns_record_set:
            zone_name: osuv.de
            name: hetzner_dns_ansible_collection
            value: 
              - "ansible.com."
            type: CNAME
            ttl: 300
            state: present
```

And then the diff is equal to `markuman.hetzner_dns`

```
TASK [community.dns | test diff on change record] *******************************************************************************************************************************************************************
--- before
+++ after
@@ -4,6 +4,6 @@
     "ttl": 300,
     "type": "CNAME",
     "value": [
-        "osuv.de."
+        "ansible.com."
     ]
 }

[DEPRECATION WARNING]: Alias 'name' is deprecated. See the module docs for more information. This feature will be removed from community.dns in version 3.0.0. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
changed: [localhost]

```

**Comment by markuman** [comment]
so the only difference in the diff handling is for new records

`markuman.hetzner_dns`

```diff
--- before
+++ after
@@ -1 +1,4 @@
-[]
+- name: blabla
+  ttl: 300
+  type: CNAME
+  value: ansible.com.
```

`community.dns`

```diff
--- before
+++ after
@@ -1 +1,7 @@
-{}
+{
+    "prefix": "blabla",
+    "record": "blabla.osuv.de",
+    "ttl": 300,
+    "type": "CNAME",
+    "value": "ansible.com."
+}

```

but I still have no preference for it.

**Comment by pgassmann** [comment]
I did some tests now and it looks great. The diff is working properly.

I found 1 issue and 2 minor things

* TTL defaults to 300 if not defined on the module. both when reading witn `record_info` and when creating entries with `record_set`! It should be omitted if the individual record has no ttl to fall back on the zone default ttl.

I also noticed that if there are 2 records with different TTLs, the current state has a `ttls` key which is not documented.

```diff
TASK [manage TXTS records] **************************************
--- before
+++ after
@@ -1,9 +1,6 @@
 prefix: ''
 record: example.me
 ttl: 300
-ttls:
-- 300
-- 400
 type: TXT
 value:
 - '"google-site-verification=asdf"'
```
(the second value is cut, its outside of the 3 lines context of the change)

Minor remarks:
- zone_info: the values legacy_ns have unstable order. could this be sorted by the module? for backups its not nice if there are unreal changes reported. I currently use a workaround in ansible:
 
```yaml
- name: fetch zone info for {{ zone }}
  community.dns.hetzner_dns_zone_info:
    zone_name: '{{ zone }}'
    api_token: '{{ hetzner_dns_api_token }}'
  register: zone_info
- name: write zone_info of {{ zone }} to file # noqa 208
  vars:
    # workaround unstable order of legacy_ns values
    _legacy_ns: '{{ zone_info.zone_info.legacy_ns | sort }}'
    _zone_info: '{{ zone_info.zone_info | combine( {"legacy_ns": _legacy_ns} ) }}'
  copy:
    content: |
      # Hetzner DNS Zone Info for {{ zone }}
      {{ _zone_info | to_nice_yaml(indent=2, width=10000) }}
    dest: '{{ hetzner_dns_backup_path }}/{{ zone }}_info.yml'
```

- list in `_record` `value` are converted to strings
  should report an error instead of implicitly serialize into a string. 

```yaml
    - name: manage TXTS records
      community.dns.hetzner_dns_record:
        api_token: '{{ hetzner_dns_api_token }}'
        zone_name: example.me
        state: present
        prefix: ''
        type: TXT
        value:
          - '"v=spf1 include:spf.protection.outlook.com include:spf.emailsignatures365.com ~all"'
          - '"google-site-verification=asdf"'
```
creates:

```diff
TASK [manage TXTS records] ***************************************
--- before
+++ after
@@ -1 +1,5 @@
-{}
+prefix: ''
+record: aviloo.me
+ttl: 300
+type: TXT
+value: '[''"v=spf1 include:spf.protection.outlook.com include:spf.emailsignatures365.com ~all"'', ''"google-site-verification=asdf"'']'
```


My backup and restore PoC plays:

(I will look at `record_sets` for restoring, instead of the loop)

```yaml
- name: Hetzner DNS Backup Play
  hosts: localhost
  tags:
    - dns_zone_backup
  tasks:
    - name: fetch zone info
      community.dns.hetzner_dns_zone_info:
        zone_name: example.me
        api_token: '{{ hetzner_dns_api_token }}'
      register: zone_info

    - name: print zone_info
      debug:
        var: zone_info
      changed_when: True

    - name: fetch record info
      community.dns.hetzner_dns_record_info:
        zone_name: example.me
        what: all_records
        api_token: '{{ hetzner_dns_api_token }}'
      register: record_info

    - name: write records to file
      copy:
        content: |
          # Hetzner DNS Zone {{ item }}
          {{ record_info.sets | to_nice_yaml(indent=2, width=10000) }}
        dest: '{{ local_cache_dir }}/dns/{{ item }}.yml'
      with_items:
        - example.me

    - name: write zone_info to file # noqa 208
      # vars:
      #   # wordaround unstable order of legacy_ns values
      #   _legacy_ns: '{{ zone_info.zone_info.legacy_ns | sort }}'
      #   _zone_info: '{{ zone_info.zone_info | combine( {"legacy_ns": _legacy_ns} ) }}'
      copy:
        content: |
          # Hetzner DNS Zone Info for {{ item }}
          {{ zone_info.zone_info | to_nice_yaml(indent=2, width=10000) }}
        dest: '{{ local_cache_dir }}/dns/{{ item }}_info.yml'
      with_items:
        - example.me


- name: Hetzner DNS Restore Play
  hosts: localhost
  tags:
    - dns_zone_restore
  tasks:
  - name: restore record_sets
    vars:
      backup_file: '{{ local_cache_dir }}/dns/example.me.yml'
      record_sets: "{{ lookup('file', backup_file) | from_yaml }}"
    community.dns.hetzner_dns_record_set:
      state: present
      zone_name: example.me
      prefix: "{{ item['prefix'] }}"
      type: "{{ item['type'] }}"
      value:  "{{ item['value'] }}"
      ttl:  "{{ item['ttl'] | default(omit) }}"
      api_token: '{{ hetzner_dns_api_token }}'
    with_items: '{{ record_sets }}'
```

**Comment by markuman** [comment]
>  It should be omitted if the individual record has no ttl to fall back on the zone default ttl.

good point.  
we discussed that already, and when you do nothing about it, hetzner api does not return TTL while the web console use default ttl of 300.  
The api docs say nothing about this point.

But I've found now where it referes to the `SOA` record:
https://docs.hetzner.com/de/dns-console/dns/general/zone-file-example/#soa-record

**Comment by felixfontein** [comment]
> > the only thing modified is the TTL.
> 
> no. TTL was not affected.

I meant by the module in general. It matches by type, prefix and value, and modifies the TTL if a matching record is found.

I'm wondering whether the module should do a more relaxed match for when it's known that there can only be one value for a given type and prefix, as for CNAME records (https://serverfault.com/questions/574072/can-we-have-multiple-cnames-for-a-single-name#574077) - and probably also SOA records. (I'm not sure if there are more record types with this property.)

**Comment by felixfontein** [comment]
> I did some tests now and it looks great. The diff is working properly.
> 
> I found 1 issue and 2 minor things
> 
>     * TTL defaults to 300 if not defined on the module. both when reading witn `record_info` and when creating entries with `record_set`! It should be omitted if the individual record has no ttl to fall back on the zone default ttl.

What is the "zone default TTL"? Is that the "Zone TTL" in the zone object (https://dns.hetzner.com/api-docs/#operation/GetZone)?

In any case, in the discussion @markuman and me had (it was on IRC and resulted in https://github.com/ansible-collections/community.dns/pull/42) we settled on that it only works well to implement TTL idempotency handling uniformly for all DNS modules if we know how to correctly interpret the missing TTL (we settled to 300 since we had no data pointing to another value).

**Comment by felixfontein** [comment]
> I also noticed that if there are 2 records with different TTLs, the current state has a `ttls` key which is not documented.

Yes, it would be good to document this. I'll create a PR for that later.

>     * zone_info: the values legacy_ns have unstable order. could this be sorted by the module? for backups its not nice if there are unreal changes reported. I currently use a workaround in ansible:

I can add sorting for that.

>     * list in `_record` `value` are converted to strings
>       should report an error instead of implicitly serialize into a string.

That's a general problem with Ansible. If you want to get an error / be informed when Ansible reinterprets things as strings, please set [STRING_CONVERSION_ACTION](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#string-conversion-action) to `error` or `warn`.

> My backup and restore PoC plays:
> 
> (I will look at `record_sets` for restoring, instead of the loop)

It's definitely more efficient, both for restoring and for ensuring that the zone's state is as in your local definition.

**Comment by felixfontein** [comment]
Another thing that should be addressed (I completely forgot about it until I found it again just now): https://github.com/ansible-collections/community.dns/pull/27#issuecomment-877849978

**Comment by felixfontein** [comment]
> > I did some tests now and it looks great. The diff is working properly.
> > I found 1 issue and 2 minor things
> > ```
> > * TTL defaults to 300 if not defined on the module. both when reading witn `record_info` and when creating entries with `record_set`! It should be omitted if the individual record has no ttl to fall back on the zone default ttl.
> > ```
> 
> What is the "zone default TTL"? Is that the "Zone TTL" in the zone object (https://dns.hetzner.com/api-docs/#operation/GetZone)?
> 
> In any case, in the discussion @markuman and me had (it was on IRC and resulted in [ansible-collections/community.dns#42](https://github.com/ansible-collections/community.dns/pull/42)) we settled on that it only works well to implement TTL idempotency handling uniformly for all DNS modules if we know how to correctly interpret the missing TTL (we settled to 300 since we had no data pointing to another value).

Ah, I now found what @markuman meant with the zone file link: "Die Einträge sind normalerweise 24 Stunden (86400 Sekunden) gültig, falls kein anderer Wert definiert wird". So we basically need the SOA record.

Unfortunately, it seems that this information is wrong. I've set that value to 543 for the SOA record in my test zone, and set the zone's TTL to 345. Then I removed `ttl` from one record. If I `dig` it, I get TTL 345; if I `dig` the SOA entry, it contains 543.

So it looks like the correct value is the zone's TTL, and not the TTL inside the SOA entry.

This is really confusing, and another reason why I want to avoid at any cost to expose the TTL default system to the end user.

**Comment by felixfontein** [comment]
> > I also noticed that if there are 2 records with different TTLs, the current state has a `ttls` key which is not documented.
> 
> Yes, it would be good to document this. I'll create a PR for that later.

https://github.com/ansible-collections/community.dns/pull/47

> > ```
> > * zone_info: the values legacy_ns have unstable order. could this be sorted by the module? for backups its not nice if there are unreal changes reported. I currently use a workaround in ansible:
> > ```
> 
> I can add sorting for that.

https://github.com/ansible-collections/community.dns/pull/46

> > ```
> > * list in `_record` `value` are converted to strings
> >   should report an error instead of implicitly serialize into a string.
> > ```
> 
> That's a general problem with Ansible. If you want to get an error / be informed when Ansible reinterprets things as strings, please set [STRING_CONVERSION_ACTION](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#string-conversion-action) to `error` or `warn`.

Turns out that this setting no longer works since ansible-core 2.11.

**Comment by pgassmann** [comment]
> What is the "zone default TTL"? Is that the "Zone TTL" in the zone object (https://dns.hetzner.com/api-docs/#operation/GetZone)?
> 
> In any case, in the discussion @markuman and me had (it was on IRC and resulted in [ansible-collections/community.dns#42](https://github.com/ansible-collections/community.dns/pull/42)) we settled on that it only works well to implement TTL idempotency handling uniformly for all DNS modules if we know how to correctly interpret the missing TTL (we settled to 300 since we had no data pointing to another value).

Default Zone TTL is not something specific to hetzner. That's a bind feature. not defined by the SOA, but by the `$TTL 86400` line at the top of the zone file. or in the UI and API its in the zone settings.
https://dns.hetzner.com/api-docs/#operation/UpdateZone
![grafik](https://user-images.githubusercontent.com/460192/127393800-1747f917-6281-41f0-b485-12ac49ea90e5.png)


Why do you need to know the default zone TTL? the TTL of a record can be empty. You can omit it in the output if it is not set. and the other way round, I would remove the ttl value if it is not set on the module or set to "" (if thats a valid value for an integer parameter)

not sure what's confusing to you. The grey value shown on the UI is just informational. Its not part of the record if you look at the zone file.

**Comment by pgassmann** [comment]
Setting the zone default TTL should be part of a separate `hetzner_dns_zone` module to create and update zones at hetzner. But I can live without that automation.

**Comment by felixfontein** [comment]
I created issues so we can discuss these things more structured than in this crowded issue:
1. TXT record handling: https://github.com/ansible-collections/community.dns/issues/48
2. CNAME/SOA(/...?) matching: https://github.com/ansible-collections/community.dns/issues/49
3. Default TTLs: https://github.com/ansible-collections/community.dns/issues/50

**Comment by felixfontein** [comment]
> Default Zone TTL is not something specific to hetzner. That's a bind feature. not defined by the SOA, but by the `$TTL 86400` line at the top of the zone file. or in the UI and API its in the zone settings.

Well, the API docs do not mention that. Which really sucks IMO.

> https://dns.hetzner.com/api-docs/#operation/UpdateZone
> ![grafik](https://user-images.githubusercontent.com/460192/127393800-1747f917-6281-41f0-b485-12ac49ea90e5.png)

Is that a screenshot from the UI? I wish the API docs would have mentioned that.

> Why do you need to know the default zone TTL? the TTL of a record can be empty. You can omit it in the output if it is not set. and the other way round, I would remove the ttl value if it is not set on the module or set to "" (if thats a valid value for an integer parameter)

I need to know it because the modules are designed in a way that they need to know the TTL to work. They need to be modified when support for such a feature is added.

> not sure what's confusing to you. The grey value shown on the UI is just informational. Its not part of the record if you look at the zone file.

I don't know the UI at all. I only know the API docs and the interactions I had with the API and with the nameservers.

**Comment by felixfontein** [comment]
I've started implementing that in https://github.com/ansible-collections/community.dns/pull/52.

In any case, comments on https://github.com/ansible-collections/community.dns/issues/48, https://github.com/ansible-collections/community.dns/issues/49, and https://github.com/ansible-collections/community.dns/issues/53 are also welcome.

**Comment by felixfontein** [comment]
community.dns 2.0.0-a2 has been released with some more breaking changes, which should improve migration. See the updated migration guide: https://ansible.fontein.de/collections/community/dns/docsite/hetzner_guide.html#migrating-from-markuman-hetzner-dns

**Comment by pgassmann** [comment]
@felixfontein @markuman thank you for your work. I noticed another difference. The module by @markuman returns additional information about a record. I use the module to create backups of the zones records. The `created` and `modified` timestamps can be useful for example to find correlation with other events/tickets to check if a specific record is still needed.

@felixfontein can you return that information too?

```yaml
- created: 2020-10-19 14:44:36.676 +0000 UTC
  id: adf8203e6319d49ff03136b4d7bbad1e
  modified: 2021-02-13 15:17:22.026 +0000 UTC
  name: '@'
  ttl: 600
  type: A
  value: 1.2.3.4
  zone_id: sRoFasdfasdfasdf
```

sorry for the delayed response. I became father 3 weeks ago.
